#SELECT CONCAT('RENAME TABLE ', `TABLE_NAME` , ' TO %DBPREFIX%',MID(`TABLE_NAME`,5), ';') AS 'sql' FROM `TABLES` WHERE `TABLE_SCHEMA` = 'ludo_master' ORDER BY `TABLE_NAME`;
RENAME TABLE mstr_action_logs TO %DBPREFIX%_action_logs;
RENAME TABLE mstr_action_logs_extensions TO %DBPREFIX%_action_logs_extensions;
RENAME TABLE mstr_action_logs_users TO %DBPREFIX%_action_logs_users;
RENAME TABLE mstr_action_log_config TO %DBPREFIX%_action_log_config;
RENAME TABLE mstr_assets TO %DBPREFIX%_assets;
RENAME TABLE mstr_associations TO %DBPREFIX%_associations;
RENAME TABLE mstr_banners TO %DBPREFIX%_banners;
RENAME TABLE mstr_banner_clients TO %DBPREFIX%_banner_clients;
RENAME TABLE mstr_banner_tracks TO %DBPREFIX%_banner_tracks;
RENAME TABLE mstr_categories TO %DBPREFIX%_categories;
RENAME TABLE mstr_contact_details TO %DBPREFIX%_contact_details;
RENAME TABLE mstr_content TO %DBPREFIX%_content;
RENAME TABLE mstr_contentitem_tag_map TO %DBPREFIX%_contentitem_tag_map;
RENAME TABLE mstr_content_frontpage TO %DBPREFIX%_content_frontpage;
RENAME TABLE mstr_content_rating TO %DBPREFIX%_content_rating;
RENAME TABLE mstr_content_types TO %DBPREFIX%_content_types;
RENAME TABLE mstr_core_log_searches TO %DBPREFIX%_core_log_searches;
RENAME TABLE mstr_extensions TO %DBPREFIX%_extensions;
RENAME TABLE mstr_fields TO %DBPREFIX%_fields;
RENAME TABLE mstr_fields_categories TO %DBPREFIX%_fields_categories;
RENAME TABLE mstr_fields_groups TO %DBPREFIX%_fields_groups;
RENAME TABLE mstr_fields_values TO %DBPREFIX%_fields_values;
RENAME TABLE mstr_finder_filters TO %DBPREFIX%_finder_filters;
RENAME TABLE mstr_finder_links TO %DBPREFIX%_finder_links;
RENAME TABLE mstr_finder_links_terms TO %DBPREFIX%_finder_links_terms;
RENAME TABLE mstr_finder_logging TO %DBPREFIX%_finder_logging;
RENAME TABLE mstr_finder_taxonomy TO %DBPREFIX%_finder_taxonomy;
RENAME TABLE mstr_finder_taxonomy_map TO %DBPREFIX%_finder_taxonomy_map;
RENAME TABLE mstr_finder_terms TO %DBPREFIX%_finder_terms;
RENAME TABLE mstr_finder_terms_common TO %DBPREFIX%_finder_terms_common;
RENAME TABLE mstr_finder_tokens TO %DBPREFIX%_finder_tokens;
RENAME TABLE mstr_finder_tokens_aggregate TO %DBPREFIX%_finder_tokens_aggregate;
RENAME TABLE mstr_finder_types TO %DBPREFIX%_finder_types;
RENAME TABLE mstr_guidedtours TO %DBPREFIX%_guidedtours;
RENAME TABLE mstr_guidedtour_steps TO %DBPREFIX%_guidedtour_steps;
RENAME TABLE mstr_history TO %DBPREFIX%_history;
RENAME TABLE mstr_languages TO %DBPREFIX%_languages;
RENAME TABLE mstr_lupo_agecategories TO %DBPREFIX%_lupo_agecategories;
RENAME TABLE mstr_lupo_categories TO %DBPREFIX%_lupo_categories;
RENAME TABLE mstr_lupo_clients TO %DBPREFIX%_lupo_clients;
RENAME TABLE mstr_lupo_clients_borrowed TO %DBPREFIX%_lupo_clients_borrowed;
RENAME TABLE mstr_lupo_game TO %DBPREFIX%_lupo_game;
RENAME TABLE mstr_lupo_game_documents TO %DBPREFIX%_lupo_game_documents;
RENAME TABLE mstr_lupo_game_editions TO %DBPREFIX%_lupo_game_editions;
RENAME TABLE mstr_lupo_game_genre TO %DBPREFIX%_lupo_game_genre;
RENAME TABLE mstr_lupo_game_related TO %DBPREFIX%_lupo_game_related;
RENAME TABLE mstr_lupo_genres TO %DBPREFIX%_lupo_genres;
RENAME TABLE mstr_lupo_reservations_web TO %DBPREFIX%_lupo_reservations_web;
RENAME TABLE mstr_mail_templates TO %DBPREFIX%_mail_templates;
RENAME TABLE mstr_menu TO %DBPREFIX%_menu;
RENAME TABLE mstr_menu_types TO %DBPREFIX%_menu_types;
RENAME TABLE mstr_messages TO %DBPREFIX%_messages;
RENAME TABLE mstr_messages_cfg TO %DBPREFIX%_messages_cfg;
RENAME TABLE mstr_modules TO %DBPREFIX%_modules;
RENAME TABLE mstr_modules_menu TO %DBPREFIX%_modules_menu;
RENAME TABLE mstr_newsfeeds TO %DBPREFIX%_newsfeeds;
RENAME TABLE mstr_overrider TO %DBPREFIX%_overrider;
RENAME TABLE mstr_postinstall_messages TO %DBPREFIX%_postinstall_messages;
RENAME TABLE mstr_privacy_consents TO %DBPREFIX%_privacy_consents;
RENAME TABLE mstr_privacy_requests TO %DBPREFIX%_privacy_requests;
RENAME TABLE mstr_redirect_links TO %DBPREFIX%_redirect_links;
RENAME TABLE mstr_scheduler_tasks TO %DBPREFIX%_scheduler_tasks;
RENAME TABLE mstr_schemaorg TO %DBPREFIX%_schemaorg;
RENAME TABLE mstr_schemas TO %DBPREFIX%_schemas;
RENAME TABLE mstr_session TO %DBPREFIX%_session;
RENAME TABLE mstr_tags TO %DBPREFIX%_tags;
RENAME TABLE mstr_template_overrides TO %DBPREFIX%_template_overrides;
RENAME TABLE mstr_template_styles TO %DBPREFIX%_template_styles;
RENAME TABLE mstr_tuf_metadata TO %DBPREFIX%_tuf_metadata;
RENAME TABLE mstr_ucm_base TO %DBPREFIX%_ucm_base;
RENAME TABLE mstr_ucm_content TO %DBPREFIX%_ucm_content;
RENAME TABLE mstr_updates TO %DBPREFIX%_updates;
RENAME TABLE mstr_update_sites TO %DBPREFIX%_update_sites;
RENAME TABLE mstr_update_sites_extensions TO %DBPREFIX%_update_sites_extensions;
RENAME TABLE mstr_usergroups TO %DBPREFIX%_usergroups;
RENAME TABLE mstr_users TO %DBPREFIX%_users;
RENAME TABLE mstr_user_keys TO %DBPREFIX%_user_keys;
RENAME TABLE mstr_user_mfa TO %DBPREFIX%_user_mfa;
RENAME TABLE mstr_user_notes TO %DBPREFIX%_user_notes;
RENAME TABLE mstr_user_profiles TO %DBPREFIX%_user_profiles;
RENAME TABLE mstr_user_usergroup_map TO %DBPREFIX%_user_usergroup_map;
RENAME TABLE mstr_viewlevels TO %DBPREFIX%_viewlevels;
RENAME TABLE mstr_webauthn_credentials TO %DBPREFIX%_webauthn_credentials;
RENAME TABLE mstr_weblinks TO %DBPREFIX%_weblinks;
RENAME TABLE mstr_wf_profiles TO %DBPREFIX%_wf_profiles;
RENAME TABLE mstr_widgetkit TO %DBPREFIX%_widgetkit;
RENAME TABLE mstr_workflows TO %DBPREFIX%_workflows;
RENAME TABLE mstr_workflow_associations TO %DBPREFIX%_workflow_associations;
RENAME TABLE mstr_workflow_stages TO %DBPREFIX%_workflow_stages;
RENAME TABLE mstr_workflow_transitions TO %DBPREFIX%_workflow_transitions;



### UPDATE DATA ###
UPDATE `%DBPREFIX%_contact_details` SET `email_to` = REPLACE(`email_to`, '{{EMAIL}}', '%EMAIL%');
UPDATE `%DBPREFIX%_users` SET `email` = REPLACE(`email`, '{{EMAIL}}', '%EMAIL%');

UPDATE `%DBPREFIX%_content` SET `introtext` = REPLACE(`introtext`, '{{LUDOTHEK}}', '%LUDOTHEK%');
UPDATE `%DBPREFIX%_content` SET `introtext` = REPLACE(`introtext`, '{{STRASSE}}', '%STRASSE%');
UPDATE `%DBPREFIX%_content` SET `introtext` = REPLACE(`introtext`, '{{PLZ_ORT}}', '%PLZ_ORT%');
UPDATE `%DBPREFIX%_content` SET `introtext` = REPLACE(`introtext`, '{{EMAIL}}', '%EMAIL%');
UPDATE `%DBPREFIX%_content` SET `introtext` = REPLACE(`introtext`, '{{TEL_LINK}}', '%TEL_LINK%');
UPDATE `%DBPREFIX%_content` SET `introtext` = REPLACE(`introtext`, '{{TEL_HUMAN}}', '%TEL_HUMAN%');
UPDATE `%DBPREFIX%_content` SET `introtext` = REPLACE(`introtext`, '{{DATENSCHUTZ_PERSON}}', '%DATENSCHUTZ_PERSON%');

UPDATE `%DBPREFIX%_content` SET `fulltext` = REPLACE(`fulltext`, '{{LUDOTHEK}}', '%LUDOTHEK%');
UPDATE `%DBPREFIX%_content` SET `fulltext` = REPLACE(`fulltext`, '{{STRASSE}}', '%STRASSE%');
UPDATE `%DBPREFIX%_content` SET `fulltext` = REPLACE(`fulltext`, '{{PLZ_ORT}}', '%PLZ_ORT%');
UPDATE `%DBPREFIX%_content` SET `fulltext` = REPLACE(`fulltext`, '{{EMAIL}}', '%EMAIL%');
UPDATE `%DBPREFIX%_content` SET `fulltext` = REPLACE(`fulltext`, '{{TEL_LINK}}', '%TEL_LINK%');
UPDATE `%DBPREFIX%_content` SET `fulltext` = REPLACE(`fulltext`, '{{TEL_HUMAN}}', '%TEL_HUMAN%');
UPDATE `%DBPREFIX%_content` SET `fulltext` = REPLACE(`fulltext`, '{{DATENSCHUTZ_PERSON}}', '%DATENSCHUTZ_PERSON%');

UPDATE `%DBPREFIX%_modules` SET `content` = REPLACE(`content`, '{{LUDOTHEK}}', '%LUDOTHEK%');
UPDATE `%DBPREFIX%_modules` SET `content` = REPLACE(`content`, '{{STRASSE}}', '%STRASSE%');
UPDATE `%DBPREFIX%_modules` SET `content` = REPLACE(`content`, '{{PLZ_ORT}}', '%PLZ_ORT%');
UPDATE `%DBPREFIX%_modules` SET `content` = REPLACE(`content`, '{{EMAIL}}', '%EMAIL%');
UPDATE `%DBPREFIX%_modules` SET `content` = REPLACE(`content`, '{{TEL_LINK}}', '%TEL_LINK%');
UPDATE `%DBPREFIX%_modules` SET `content` = REPLACE(`content`, '{{TEL_HUMAN}}', '%TEL_HUMAN%');
UPDATE `%DBPREFIX%_modules` SET `content` = REPLACE(`content`, '{{DATENSCHUTZ_PERSON}}', '%DATENSCHUTZ_PERSON%');

UPDATE `%DBPREFIX%_widgetkit` SET `data` = REPLACE(`data`, '{{LUDOTHEK}}', '%LUDOTHEK%');
UPDATE `%DBPREFIX%_widgetkit` SET `data` = REPLACE(`data`, '{{STRASSE}}', '%STRASSE%');
UPDATE `%DBPREFIX%_widgetkit` SET `data` = REPLACE(`data`, '{{PLZ_ORT}}', '%PLZ_ORT%');
UPDATE `%DBPREFIX%_widgetkit` SET `data` = REPLACE(`data`, '{{EMAIL}}', '%EMAIL%');
UPDATE `%DBPREFIX%_widgetkit` SET `data` = REPLACE(`data`, '{{TEL_LINK}}', '%TEL_LINK%');
UPDATE `%DBPREFIX%_widgetkit` SET `data` = REPLACE(`data`, '{{TEL_HUMAN}}', '%TEL_HUMAN%');
UPDATE `%DBPREFIX%_widgetkit` SET `data` = REPLACE(`data`, '{{DATENSCHUTZ_PERSON}}', '%DATENSCHUTZ_PERSON%');

